trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /parameters/main-stages.yaml

pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  jobs:
  - template: /parameters/template-job.yaml
    parameters:
      env: dev

- stage: QA
  dependsOn: Dev
  condition: succeeded()
  jobs:
  - template: /parameters/template-job.yaml
    parameters:
      env: qa

- stage: UAT
  dependsOn: QA
  condition: succeeded()
  jobs:
  - template: /parameters/template-job.yaml
    parameters:
      env: uat

- stage: Preprod
  jobs:
  - template: /parameters/template-job.yaml
    parameters:
      env: preprod

- stage: Production
  dependsOn: UAT
  condition: failed()
  jobs:
  - template: /parameters/template-job.yaml
    parameters:
      env: production
