name: Three-stage workflow

on:
  push:
    branches:
      - main

jobs:
  stage_1:
    name: Stage 1
    runs-on: ubuntu-latest

    steps:
      - job_1:
          name: Job 1
          run: echo "Hello Code!"
      - job_2:
          name: Job 2
          run: echo "Hello Code!"

  stage_2:
    name: Stage 2
    needs:
      - stage_1
    runs-on: macos-latest

    steps:
      - job_3:
          name: Job 3
          run: echo "Hello Code!"
      - job_4:
          name: Job 4
          run: echo "Hello Code!"

  stage_3:
    name: Stage 3
    needs:
      - stage_2
    runs-on: windows-latest

    steps:
      - job_5:
          name: Job 5
          run: echo "Hello Code!"
      - job_6:
          name: Job 6
          run: echo "Hello Code!"
