name: Three-stage workflow with uses and run keys

on:
  push:
    branches:
      - main

jobs:
  stage_1:
    name: Stage 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - job_1:
          name: Job 1
          run: echo "Hello Code from Ubuntu!"

  stage_2:
    name: Stage 2
    needs:
      - stage_1
    runs-on: macos-latest

    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - job_3:
          name: Job 3
          run: dotnet test

  stage_3:
    name: Stage 3
    needs:
      - stage_2
    runs-on: windows-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - job_5:
          name: Job 5
          run: npm run test
